# Generated by Django 6.0.7 on 2026-07-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0001_initial'),
        ('servicos', '0002_categoria_servico_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='servicos',
            field=models.ManyToManyField(to='servicos.servico'),
        ),
    ]
